export default {
  Colors: {
    WHITE: '#FFFFFF',
    BLACK: '#000000',
    BLUE: '#0076ce',
    BACKGROUND: '#FFFFFF',
    INPUT_TEXT_COLOR: '#000000',
    PLACEHOLDER_COLOR: '#A5A5A5',
    BUTTON_COLOR: '#8967C7',
    BORDER_BUTTON_COLOR: '#8967C7',
    FONT_COLOR: '#FFFFFF',
    ICON_COLOR_INPUT: '#8967C7',
    ICON_COLOR: '#FFFFFF',
    HEADER_COLOR: '#8967C7',
  },

  Sizes: {
    FONTSIZE_BUTTON: 20,
    FONTSIZE_TEXT: 22,
    ICON_SIZE: 25,
    ICON_SIZE_FILTER_BAR: 20,
    ICON_SIZE_HEADER: 30,
  },
};
